# Generated by Django 4.0.4 on 2022-05-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='created',
        ),
    ]
