# Generated by Django 4.0.4 on 2022-06-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_remove_users_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='is_win',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='finalprice',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='model_year',
            field=models.IntegerField(),
        ),
    ]
